### ISSUE TITLE
i use this  monitoring can't in chinese 

### ISSUE THREAD

**Issue by zqc0512** [anbai-inc/Kibana_Hanization#10]
@anbai-inc 
kibana is 5.6.8 thanks.
like this:
![image](https://user-images.githubusercontent.com/25192261/38078514-21e5cbf0-336f-11e8-8867-29f01e695c77.png)

**Comment by SwordSheath** [comment]
仅对Kibana做了汉化，没有对Kibana的插件做汉化。后面有时间的话会考虑加入。

**Comment by zhoudanwei** [comment]
老哥,在么,你这个再python3,无法运行,有问题的.具体出错的地方在:
19行,29行,46行,原因是因为python3可能要设置文件编码?
加上encoding="utf-8"貌似就好了,具体的你看看吧
f = open("./config/kibana_resource.json", "r",encoding='utf-8')
