### ISSUE TITLE
汉化命令没有反应

### ISSUE THREAD

**Issue by sjoooo123** [anbai-inc/Kibana_Hanization#20]
运行：python main.py G:\project\kibana-6.3.2之后，一直处于运行状态，长时间不动，如下图：
![360 16341019272116](https://user-images.githubusercontent.com/22810581/45406357-c9b27480-b698-11e8-957c-2904573d4658.jpg)，
待汉化版本：6.3.2开发版（就是从github上拉下来的，不是产品版），
请问这种情况大概是什么原因呢？

**Comment by SwordSheath** [comment]
可能是Windows路径表示与linux不相同导致的，如D:\和/root/，在进行字符串比对的时候会出现问题。
