### ISSUE TITLE
Kibana6.1.3汉化后仪表盘菜单里添加按钮点击无效并报错

### ISSUE THREAD

**Issue by JoeyBling** [anbai-inc/Kibana_Hanization#21]
https://upload-images.jianshu.io/upload_images/2743275-6a52923d715eb924.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by SwordSheath** [comment]
请点击工具栏中的"添加"。

**Comment by JoeyBling** [comment]
但是这个问题还是没有解决，算是一个缺陷了
