### ISSUE TITLE
系统监控菜单栏是怎么显示的?

### ISSUE THREAD

**Issue by JoeyBling** [anbai-inc/Kibana_Hanization#22]
系统监控菜单栏是怎么显示的?
我只有这几个
https://upload-images.jianshu.io/upload_images/2743275-cf013a90d60f9431.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by SwordSheath** [comment]
老版本请安装xpack插件，新版本Kibana默认自带。
