### ISSUE TITLE
汉化Kibana时出错，错误：'gbk' codec can't decode byte 0xaf in position 232: illegal multibyte sequence

### ISSUE THREAD

**Issue by geekyouth** [anbai-inc/Kibana_Hanization#23]
win10 cmd 切换 utf8 ：chcp 65001

Active code page: 65001

D:\0-code\Kibana_Hanization>python main.py D:\kibana-6.0.0-linux-x86_64
汉化Kibana时出错，错误：'gbk' codec can't decode byte 0xaf in position 232: illegal multibyte sequence

![image](https://user-images.githubusercontent.com/12899262/46421626-169fdd00-c765-11e8-8bdb-9ae6c07cb5b6.png)

**Comment by geekyouth** [comment]
使用linux 执行，一步搞定，win10 并不适合作为完美的开发环境

**Comment by Sky-Data** [comment]
window环境下出现这种问题是无解？

**Comment by Sky-Data** [comment]
和python版本也有关系，使用27版本的不会报错，但是编译是乱码。
