### ISSUE TITLE
汉化可逆

### ISSUE THREAD

**Issue by ZJLTQ** [anbai-inc/Kibana_Hanization#25]
content = content.replace(en, cn)  # 替换要翻译的文字  
这里en,cn 互换是不是就汉化可逆了

**Comment by herozabbix** [comment]
成功了吗

**Comment by zqc0512** [comment]
做之间备份kibana就行了。
或者多起几个kibana。一个中文，一个英文。

**Comment by SwordSheath** [comment]
之前不是没有考虑过可逆还原，看似可以反过来将中文还原成英文的，其实是有问题的，比如：
xx yy zz ---> 中国人
xx yy      ---> 中国
xx yy kk ---> 中国地
这两具都是单独翻译过来的，如过返过来还原，则<中国地>可能被翻译回<xx yy地>，从而导致还原失败。
因为翻译中涉及很多长句，所以这个问题就更加明显。所以最终并未做还原翻译的功能。因为备份Kibana显然更简单粗暴。
