### ISSUE TITLE
kibana汉化后可选字段不见了

### ISSUE THREAD

**Issue by liuhaibo0303** [anbai-inc/Kibana_Hanization#29]
如题，kibana汉化后，用于筛选展示的可选字段没有了，如下图
![image](https://user-images.githubusercontent.com/32126569/48040948-1062ad80-e1b6-11e8-8eb4-ea692aabfd81.png)

**Comment by SwordSheath** [comment]
可否提供下Kibana的版本？

**Comment by SwordSheath** [comment]
之前出过这个问题，并修复过。在最新的kibana 6.5.1中测试，不存在该问题。您可以尝试重新下载kibana并使用最新的汉化代码去汉化。若还是有问题，可以向我反馈。
