### ISSUE TITLE
自动刷新那块的没有汉化

### ISSUE THREAD

**Issue by softxiang** [anbai-inc/Kibana_Hanization#30]
6.2.3

其他大致都差不多了，自动刷新时间那块没有汉化，虽然很简单，还是希望你有空的时候搞一下

![image](https://user-images.githubusercontent.com/4629098/48522902-44745780-e8b5-11e8-8592-69f5c426dc4f.png)

**Comment by SwordSheath** [comment]
@softxiang 已在kibana 6.5.1中测试并添加该部分汉化资源。

**Comment by SwordSheath** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/21040108/49059420-cb291d00-f243-11e8-98f6-8205df64f579.png">
