### ISSUE TITLE
关于6.5.2的翻译不全

### ISSUE THREAD

**Issue by zengwenzi** [anbai-inc/Kibana_Hanization#31]
关于6.5.2的翻译不全
你好，请问你有6.5.2的汉化吗？

**Comment by SwordSheath** [comment]
6.x的最新版是会汉化不全的，因为年底工作忙，没有时间跟。Kibana和ES官方更新的太快，基本1-2周一个小版本，个人想跟上进度还是有些难的。年后会更新汉化方法，使用Kibana官方提供的方法汉化，避免跨版本同一汉化资源失效问题。
