### ISSUE TITLE
有没有带sentinl 到kibana包，提供一个，百度云盘都可以

### ISSUE THREAD

**Issue by ithjz** [anbai-inc/Kibana_Hanization#33]
有没有带sentinl 到kibana包，提供一个，百度云盘都可以

我安装插件失败了好几次，卡着不动了

sh kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.3.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-6.5.0-0/sentinl-v6.5.3.zip
Transferring 134205068 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...

**Comment by SwordSheath** [comment]
这个项目仅仅是对Kibana进行汉化，不带任何插件。所以没有。
