### ISSUE TITLE
汉化版本

### ISSUE THREAD

**Issue by MarlonYJG** [anbai-inc/Kibana_Hanization#36]
你好
  请问你图片上展示汉化完整的是哪个版本？目前我本地的是6.6版本，显示的汉化不全。

**Comment by cs2393629** [comment]
同问，6.6的版本只能汉化一小部分

**Comment by SwordSheath** [comment]
在做正式的汉化包，使用官方的汉化方法。工作较忙，业余时间来汉化，所以不要着急，后面会给汉化包的。
