### ISSUE TITLE
这个项目还持续下去吗

### ISSUE THREAD

**Issue by R1hug0** [anbai-inc/Kibana_Hanization#37]
RT

**Comment by SwordSheath** [comment]
会，因为Kibana官方已经给了原生的汉化方法了，在6.x的版本已经支持，目前已经在做新版本的正式汉化包了。因为工作太忙，家里事太多，所以一直没有更新。这个项目当前的暴力汉化方法不再更新，后面会直接给汉化资源文件，修改配置文件kibana.yml中的配置i18n.locale: "zh_CN"即可直接使用。
