### ISSUE TITLE
6.6.2版，文件放上去，配置文件也改了，但是重启不生效

### ISSUE THREAD

**Issue by zengqiyan** [anbai-inc/Kibana_Hanization#39]

**Comment by KingzCheung** [comment]
路径不对，文档写错了。应该是 

`src/legacy/core_plugins/kibana/translations/zh_CN.json`

参见: https://github.com/elastic/kibana/blob/master/packages/kbn-i18n/README.md

**Comment by SwordSheath** [comment]
请详细阅读本项目的README，确定您的理解无误后若还是不能成功翻译，可再反馈。
