### ISSUE TITLE
old文件夹内只支持对打包后的 optimize 目录进行汉化？

### ISSUE THREAD

**Issue by Dreamer-Somebody** [anbai-inc/Kibana_Hanization#40]
开发背景：kibana 6.3.2开发版 二次开发。
问题：使用old目录里面提供的方法，发现翻译资源文件里面，大多是对编译后的资源进行翻译，那每次编译后都需要运行一遍翻译？为何不直接对src目录进行翻译？还是我理解错了呢？
先感谢一下作者提供的资源 (❁´◡`❁)*✲ﾟ*。

**Comment by Dreamer-Somebody** [comment]
不对 src 直接翻译是避免不同版本的文件位置内容不一样吗？

**Comment by SwordSheath** [comment]
因为old目录下的翻译方法是暴力替换字符串，有一定的概率破坏您的js语法结构导致Kibana不能运行。在未完全测试Kibana各个小版本的情况下，只敢汉化编译后的资源。
