### ISSUE TITLE
7.x 官方汉化方法

### ISSUE THREAD

**Issue by ykfq** [anbai-inc/Kibana_Hanization#41]
本项目中的方法对于汉化 7.x 已经不生效了，经过摸索我找到汉化 7.x 的方法，分享一下。

7.0 自带 x-pack 和 中文语言包 `zh-CN.json`, 但默认没有启用。
启用方法：
```
vim /etc/kibana/kibana.yml
i18n.locale: "zh-CN"

systemctl restart kibana
```
这里是 `zh-CN` 不是 `zh_CN`，必须和下面的 json 文件名一致：
> /usr/share/kibana/node_modules/x-pack/plugins/translations/translations/zh-CN.json

当然，自带的汉化文件没有本项目提供的完善，我们可以使用本项目的文件进行替换，注意 `i18n.locale` 设置为对应的名字。

官方文档详见：
https://github.com/elastic/kibana/tree/master/packages/kbn-i18n

**Comment by caolist** [comment]
准备试一试看，谢谢。

**Comment by sqzxcv** [comment]
> 本项目中的方法对于汉化 7.x 已经不生效了，经过摸索我找到汉化 7.x 的方法，分享一下。
> 
> 7.0 自带 x-pack 和 中文语言包 `zh-CN.json`, 但默认没有启用。
> 启用方法：
> 
> ```
> vim /etc/kibana/kibana.yml
> i18n.locale: "zh-CN"
> 
> systemctl restart kibana
> ```
> 这里是 `zh-CN` 不是 `zh_CN`，必须和下面的 json 文件名一致：
> 
> > /usr/share/kibana/node_modules/x-pack/plugins/translations/translations/zh-CN.json
> 
> 当然，自带的汉化文件没有本项目提供的完善，我们可以使用本项目的文件进行替换，注意 `i18n.locale` 设置为对应的名字。
> 
> 官方文档详见：
> https://github.com/elastic/kibana/tree/master/packages/kbn-i18n

7.0 汉化是否需要额外转插件? 我是用docker 镜像sebp/elk安装 7.0版本, 默认不带插件(在镜像内部也没有目录/usr/share/kibana/node_modules/x-pack/plugins/translations/translations/zh-CN.json), 需要额外赚什么插件吗?

**Comment by SwordSheath** [comment]
@ykfq 感谢，已处理并合并了汉化资源，其实官方的汉化资源更为完整。
