### ISSUE TITLE
老铁6666，6.1版本亲测，没毛病。

### ISSUE THREAD

**Issue by 281889448** [anbai-inc/Kibana_Hanization#5]
给楼主点个赞

**Comment by eryajf** [comment]
你好，我测试了，但是没有效果，是跟我用rpm安装的有关系吗

**Comment by SwordSheath** [comment]
可能你指定的Kibana路径不对吧，Kibana最好还是直接从官网下载zip包解压了直接用吧。

**Comment by eryajf** [comment]
我当时是rpm安装的，后来用源码安装的测试了一下，发现是可以的。
------------------------------------------------------------------发件人：RedFree <notifications@github.com>发送时间：2018年3月2日(星期五) 15:33收件人：anbai-inc/Kibana_Hanization <Kibana_Hanization@noreply.github.com>抄　送：李启龙 <liqilong@edspay.com>; Comment <comment@noreply.github.com>主　题：Re: [anbai-inc/Kibana_Hanization] 老铁6666，6.1版本亲测，没毛病。 (#5)
可能你指定的Kibana路径不对吧，Kibana最好还是直接从官网下载zip包解压了直接用吧。
