### ISSUE TITLE
Kibana_resource.json - Timelion

### ISSUE THREAD

**Issue by tobywu6652** [anbai-inc/Kibana_Hanization#7]
"path": "src/core_plugins/timelion/index.js",
    "en": "title: 'Timelion'",
    "cn": "title: '时间线'"

感觉Timelion还是不用翻译了。

**Comment by SwordSheath** [comment]
因为左边功能都是中文，就剩一个单词总感觉怪怪的，这个词又不太好用中文来翻译，所以直接就用了个接近的中文代替了。
