### ISSUE TITLE
部分汉化和你的截图不一样

### ISSUE THREAD

**Issue by taowu82** [anbai-inc/Kibana_Hanization#8]
我kibana有安装x-pack，汉化完成后发现有不少没汉化，但是看你的图有些又汉化了的

**Comment by SwordSheath** [comment]
Kibana 5.x和Kibana 6.x的部分资源已经变动，我只能尽量的去做兼容，但目前一直跟进的是最新6.x版本的Kibana。x-pack属于插件部分，后面会考虑汉化，但目前未做任何处理。

**Comment by bopo** [comment]
我觉得，可以做成多个版本的，支持不同版本的。
通过main.py 去检查 kibana 的版本，然后针对不同版本用不同 kibana_resource.json 文件进行汉化。

这个是我的一点不成熟的建议。
如果有兴趣搞朋友，可以加我Q39317679，大家一起集思广益

**Comment by SwordSheath** [comment]
ES和Kibana平均1-2周更新一个小版本，单凭一个或几个人的力量去做不同版本的汉化是不现实的，只能尽量兼容各个版本和跟最新的版本。
